/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Root */
        get: operations["root__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_api_v1_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Current User */
        get: operations["current_user_api_v1_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout */
        post: operations["logout_api_v1_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Users */
        get: operations["list_users_api_v1_users_get"];
        put?: never;
        /** Create User */
        post: operations["create_user_api_v1_users_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/{user_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get User */
        get: operations["get_user_api_v1_users__user_id__get"];
        /** Update User */
        put: operations["update_user_api_v1_users__user_id__put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/{user_id}/reset-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reset Password */
        post: operations["reset_password_api_v1_users__user_id__reset_password_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/{user_id}/disable": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Disable User */
        post: operations["disable_user_api_v1_users__user_id__disable_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/products": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Products */
        get: operations["list_products_api_v1_products_get"];
        put?: never;
        /** Create Product */
        post: operations["create_product_api_v1_products_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/products/{product_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Product */
        get: operations["get_product_api_v1_products__product_id__get"];
        /** Update Product */
        put: operations["update_product_api_v1_products__product_id__put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/products/{product_id}/disable": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Disable Product */
        post: operations["disable_product_api_v1_products__product_id__disable_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/products/{product_id}/versions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Versions */
        get: operations["list_versions_api_v1_products__product_id__versions_get"];
        put?: never;
        /** Create Version */
        post: operations["create_version_api_v1_products__product_id__versions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/products/{product_id}/versions/{version_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Version */
        get: operations["get_version_api_v1_products__product_id__versions__version_id__get"];
        /** Update Version */
        put: operations["update_version_api_v1_products__product_id__versions__version_id__put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/products/{product_id}/versions/{version_id}/disable": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Disable Version */
        post: operations["disable_version_api_v1_products__product_id__versions__version_id__disable_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/ots-components": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Ots */
        get: operations["list_ots_api_v1_ots_components_get"];
        put?: never;
        /** Create Ots */
        post: operations["create_ots_api_v1_ots_components_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/ots-components/{ots_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Ots */
        get: operations["get_ots_api_v1_ots_components__ots_id__get"];
        /** Update Ots */
        put: operations["update_ots_api_v1_ots_components__ots_id__put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/ots-components/{ots_id}/product-versions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Associated Versions */
        get: operations["associated_versions_api_v1_ots_components__ots_id__product_versions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/product-versions/{version_id}/ots": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Product Ots */
        get: operations["list_product_ots_api_v1_product_versions__version_id__ots_get"];
        put?: never;
        /** Create Product Ots */
        post: operations["create_product_ots_api_v1_product_versions__version_id__ots_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/product-versions/{version_id}/ots/{relation_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Remove Product Ots */
        delete: operations["remove_product_ots_api_v1_product_versions__version_id__ots__relation_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/product-ots/template": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Product Ots Template */
        get: operations["product_ots_template_api_v1_product_ots_template_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/product-versions/{version_id}/ots/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Export Product Ots */
        get: operations["export_product_ots_api_v1_product_versions__version_id__ots_export_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/product-versions/{version_id}/ots/import": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Import Product Ots */
        post: operations["import_product_ots_api_v1_product_versions__version_id__ots_import_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/{user_id}/scopes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List User Scopes */
        get: operations["list_user_scopes_api_v1_users__user_id__scopes_get"];
        put?: never;
        /** Grant User Scope */
        post: operations["grant_user_scope_api_v1_users__user_id__scopes_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/{user_id}/scopes/{scope_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Revoke User Scope */
        delete: operations["revoke_user_scope_api_v1_users__user_id__scopes__scope_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/scopes/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Current Scope Summary */
        get: operations["current_scope_summary_api_v1_scopes_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/collector-scope": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Preview Collector Scope */
        get: operations["preview_collector_scope_api_v1_collector_scope_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/collector-scope/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Export Collector Scope */
        get: operations["export_collector_scope_api_v1_collector_scope_export_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/import-packages/validate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Validate Import Package */
        post: operations["validate_import_package_api_v1_import_packages_validate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/import-packages/{batch_id}/confirm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Confirm Import Package */
        post: operations["confirm_import_package_api_v1_import_packages__batch_id__confirm_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/import-packages/{batch_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Import Package */
        get: operations["get_import_package_api_v1_import_packages__batch_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/import-packages/{batch_id}/errors": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Download Import Package Errors */
        get: operations["download_import_package_errors_api_v1_import_packages__batch_id__errors_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/import-packages/{batch_id}/ots-match-preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Preview */
        get: operations["preview_api_v1_import_packages__batch_id__ots_match_preview_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/import-packages/{batch_id}/ots-matches": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Execute */
        post: operations["execute_api_v1_import_packages__batch_id__ots_matches_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/import-packages/{batch_id}/ots-match-result": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Result */
        get: operations["result_api_v1_import_packages__batch_id__ots_match_result_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/vulnerabilities/{vulnerability_id}/ots-matches": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Detail */
        get: operations["detail_api_v1_vulnerabilities__vulnerability_id__ots_matches_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workbench/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Workbench Summary */
        get: operations["workbench_summary_api_v1_workbench_summary_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workbench/import-summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Import Summary */
        get: operations["import_summary_api_v1_workbench_import_summary_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/assessments/tasks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Assessment Tasks */
        get: operations["assessment_tasks_api_v1_assessments_tasks_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/vulnerabilities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Vulnerabilities */
        get: operations["vulnerabilities_api_v1_vulnerabilities_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/vulnerabilities/{vulnerability_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Vulnerability Detail */
        get: operations["vulnerability_detail_api_v1_vulnerabilities__vulnerability_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AssessmentTaskPageResponse */
        AssessmentTaskPageResponse: {
            /** Items */
            items: components["schemas"]["AssessmentTaskResponse"][];
            /** Total */
            total: number;
            /** Page */
            page: number;
            /** Page Size */
            page_size: number;
        };
        /** AssessmentTaskResponse */
        AssessmentTaskResponse: {
            /** Assessment Id */
            assessment_id: number;
            /** Vulnerability Id */
            vulnerability_id: number;
            /** Revision No */
            revision_no: number;
            /**
             * Status
             * @enum {string}
             */
            status: "pending" | "returned" | "reassess" | "submitted";
            /** Cve Id */
            cve_id: string;
            /** Product Id */
            product_id: number;
            /** Product Name */
            product_name: string;
            /** Product Version Id */
            product_version_id: number;
            /** Version No */
            version_no: string;
            /** Product Ots Id */
            product_ots_id: number;
            /** Ots Component Id */
            ots_component_id: number;
            /** Ots Name */
            ots_name: string;
            /** Ots Version */
            ots_version: string;
            /** Owner Id */
            owner_id: number;
            /** Reviewer Id */
            reviewer_id: number;
            /** Source Severity */
            source_severity: string | null;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** Body_validate_import_package_api_v1_import_packages_validate_post */
        Body_validate_import_package_api_v1_import_packages_validate_post: {
            /** File */
            file: string;
        };
        /** CandidateDetailResponse */
        CandidateDetailResponse: {
            /** Vulnerability Id */
            vulnerability_id: number;
            /** Cve Id */
            cve_id: string;
            /** Ots Component Id */
            ots_component_id: number;
            /** Ots Name */
            ots_name: string;
            /** Ots Version */
            ots_version: string;
            /** Match Method */
            match_method: string;
            /** Match Basis */
            match_basis: string;
            /** Match Confidence */
            match_confidence: number | null;
            /** Match Evidence */
            match_evidence: {
                [key: string]: unknown;
            };
            /** First Seen Batch Id */
            first_seen_batch_id: number;
            /** First Seen Batch No */
            first_seen_batch_no?: string | null;
            /** Last Seen Batch Id */
            last_seen_batch_id: number;
            /** Last Seen Batch No */
            last_seen_batch_no?: string | null;
            /** Based On Source Modified At */
            based_on_source_modified_at?: string | null;
        } & {
            [key: string]: unknown;
        };
        /** CandidateSampleResponse */
        CandidateSampleResponse: {
            /** Vulnerability Id */
            vulnerability_id: number;
            /** Cve Id */
            cve_id: string;
            /** Ots Component Id */
            ots_component_id: number;
            /** Ots Name */
            ots_name: string;
            /** Ots Version */
            ots_version: string;
            /** Match Method */
            match_method: string;
            /** Match Basis */
            match_basis: string;
            /** Match Confidence */
            match_confidence: number | null;
            /** Match Evidence */
            match_evidence: {
                [key: string]: unknown;
            };
        } & {
            [key: string]: unknown;
        };
        /** CollectorScopeBaselineResponse */
        CollectorScopeBaselineResponse: {
            /** Available */
            available: boolean;
            /** Batch No */
            batch_no: string | null;
            /** Finished At */
            finished_at: string | null;
        };
        /** CollectorScopeChangesResponse */
        CollectorScopeChangesResponse: {
            /** Added Ots Ids */
            added_ots_ids: number[];
            /** Removed Ots Ids */
            removed_ots_ids: number[];
            /** Added Count */
            added_count: number;
            /** Removed Count */
            removed_count: number;
        };
        /** CollectorScopeItemResponse */
        CollectorScopeItemResponse: {
            /** Ots Id */
            ots_id: number;
            /** Ots Name */
            ots_name: string;
            /** Ots Version */
            ots_version: string;
            /** Official Website */
            official_website: string;
            /** Last Covered Time */
            last_covered_time: string | null;
            /** Is Initial Collection */
            is_initial_collection: boolean;
        };
        /** CollectorScopePreviewResponse */
        CollectorScopePreviewResponse: {
            /** Scope Count */
            scope_count: number;
            /** Items */
            items: components["schemas"]["CollectorScopeItemResponse"][];
            comparison_baseline: components["schemas"]["CollectorScopeBaselineResponse"];
            changes: components["schemas"]["CollectorScopeChangesResponse"];
        };
        /** CsvImportResultResponse */
        CsvImportResultResponse: {
            /** Created Ots */
            created_ots: number;
            /** Created Relations */
            created_relations: number;
            /** Existing Relations */
            existing_relations: number;
        };
        /** Cvss31Response */
        Cvss31Response: {
            /** Score */
            score: number;
            /** Severity */
            severity: string | null;
            /** Vector */
            vector: string | null;
            /** Source */
            source: string | null;
        };
        /** DisableRequest */
        DisableRequest: {
            /** Row Version */
            row_version: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** ImportBatchSummaryResponse */
        ImportBatchSummaryResponse: {
            /** Id */
            id: number;
            /** Batch No */
            batch_no: string;
            /**
             * Status
             * @enum {string}
             */
            status: "succeeded" | "failed";
            /** Finished At */
            finished_at: string | null;
            /** Error Code */
            error_code?: string | null;
            /**
             * Error Count
             * @default 0
             */
            error_count: number;
        };
        /** ImportPackageResponse */
        ImportPackageResponse: {
            /** Id */
            id: number;
            /** Batch No */
            batch_no: string;
            /** Format Version */
            format_version: string;
            /** Package File Name */
            package_file_name: string;
            /** Package Sha256 */
            package_sha256: string;
            /** Status */
            status: string;
            /** Source Name */
            source_name: string | null;
            /** Source Release */
            source_release: string | null;
            /** Window Start */
            window_start: string | null;
            /** Window End */
            window_end: string | null;
            /** Classification Basis */
            classification_basis: string;
            /** Final Import Diff */
            final_import_diff: boolean;
            /** Can Import */
            can_import: boolean;
            /** Internal Matching Pending */
            internal_matching_pending: boolean;
            summary: components["schemas"]["PackageSummaryResponse"];
            /** File Stats */
            file_stats: {
                [key: string]: components["schemas"]["PackageFileStatsResponse"];
            };
            /** Errors */
            errors: components["schemas"]["PackageValidationIssueResponse"][];
            /** Total Error Count */
            total_error_count: number;
            /** Truncated Error Count */
            truncated_error_count: number;
            /** Duplicate */
            duplicate: boolean;
        };
        /** ImportSummaryResponse */
        ImportSummaryResponse: {
            latest_succeeded: components["schemas"]["ImportBatchSummaryResponse"] | null;
            latest_failed: components["schemas"]["ImportBatchSummaryResponse"] | null;
            /** Last Successful Import At */
            last_successful_import_at: string | null;
            /**
             * Coverage Status
             * @enum {string}
             */
            coverage_status: "available" | "not_provided";
            /** Last Covered Time */
            last_covered_time: string | null;
        };
        /** KevResponse */
        KevResponse: {
            /** Is Kev */
            is_kev: boolean;
            /** Date Added */
            date_added: string | null;
            /** Due Date */
            due_date: string | null;
            /** Required Action */
            required_action: string | null;
        };
        /** LoginRequest */
        LoginRequest: {
            /** Login Name */
            login_name: string;
            /** Password */
            password: string;
        };
        /** MatchSummaryResponse */
        MatchSummaryResponse: {
            /** Schema Version */
            schema_version: string;
            /** Status */
            status: string;
            /** Matching Rule Version */
            matching_rule_version: string;
            /** Version Rule Version */
            version_rule_version: string;
            /** Processed Vulnerability Count */
            processed_vulnerability_count: number;
            /** Candidate Inserted Count */
            candidate_inserted_count: number;
            /** Candidate Updated Count */
            candidate_updated_count: number;
            /** Candidate Removed Count */
            candidate_removed_count: number;
            /** Candidate Unchanged Count */
            candidate_unchanged_count: number;
            /** Unmatched Vulnerability Count */
            unmatched_vulnerability_count: number;
            /** Unmatched Reason Counts */
            unmatched_reason_counts: {
                [key: string]: number;
            };
            /** Unmatched Samples */
            unmatched_samples: {
                [key: string]: unknown;
            }[];
            /** Truncated Unmatched Count */
            truncated_unmatched_count: number;
            /** Candidate Samples */
            candidate_samples: components["schemas"]["CandidateSampleResponse"][];
            /** Truncated Candidate Count */
            truncated_candidate_count: number;
            /** Candidate Disclaimer */
            candidate_disclaimer: string;
            /** Error Code */
            error_code: string | null;
            /** Finished At */
            finished_at: string | null;
            task_generation: components["schemas"]["TaskGenerationResponse"];
        } & {
            [key: string]: unknown;
        };
        /** OtsCreateRequest */
        OtsCreateRequest: {
            /** Ots Name */
            ots_name: string;
            /** Ots Version */
            ots_version: string;
            /** Official Website */
            official_website: string;
            /** Is Eol */
            is_eol: boolean;
        };
        /** OtsPageResponse */
        OtsPageResponse: {
            /** Items */
            items: components["schemas"]["OtsResponse"][];
            /** Total */
            total: number;
            /** Page */
            page: number;
            /** Page Size */
            page_size: number;
        };
        /** OtsProductVersionResponse */
        OtsProductVersionResponse: {
            /** Product Ots Id */
            product_ots_id: number;
            /** Product Id */
            product_id: number;
            /** Product Code */
            product_code: string;
            /** Product Name */
            product_name: string;
            /** Product Version Id */
            product_version_id: number;
            /** Version No */
            version_no: string;
            /** Status */
            status: string;
        };
        /** OtsResponse */
        OtsResponse: {
            /** Id */
            id: number;
            /** Ots Name */
            ots_name: string;
            /** Ots Version */
            ots_version: string;
            /** Official Website */
            official_website: string;
            /** Is Eol */
            is_eol: boolean;
            /** Row Version */
            row_version: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** OtsUpdateRequest */
        OtsUpdateRequest: {
            /** Ots Name */
            ots_name: string;
            /** Ots Version */
            ots_version: string;
            /** Official Website */
            official_website: string;
            /** Is Eol */
            is_eol: boolean;
            /** Row Version */
            row_version: number;
        };
        /** PackageFileStatsResponse */
        PackageFileStatsResponse: {
            /** Total */
            total: number;
            /** New */
            new: number;
            /** Update */
            update: number;
            /** Duplicate */
            duplicate: number;
            /** Conflict */
            conflict: number;
            /** Error */
            error: number;
            /** Samples */
            samples: {
                [key: string]: unknown;
            }[];
        };
        /** PackageSummaryResponse */
        PackageSummaryResponse: {
            /** Total */
            total: number;
            /** New */
            new: number;
            /** Update */
            update: number;
            /** Duplicate */
            duplicate: number;
            /** Conflict */
            conflict: number;
            /** Error */
            error: number;
        };
        /** PackageValidationIssueResponse */
        PackageValidationIssueResponse: {
            /** Error Code */
            error_code: string;
            /** File Name */
            file_name: string;
            /** Row Number */
            row_number: number | null;
            /** Field */
            field: string | null;
            /** Reason */
            reason: string;
            /** Rejected Value */
            rejected_value: string | null;
        };
        /** PasswordResetRequest */
        PasswordResetRequest: {
            /** Password */
            password: string;
            /** Row Version */
            row_version: number;
        };
        /** ProductCreateRequest */
        ProductCreateRequest: {
            /** Product Code */
            product_code: string;
            /** Product Name */
            product_name: string;
            /** Description */
            description?: string | null;
        };
        /** ProductOtsCreateRequest */
        ProductOtsCreateRequest: {
            /** Ots Component Id */
            ots_component_id: number;
        };
        /** ProductOtsResponse */
        ProductOtsResponse: {
            /** Id */
            id: number;
            /** Product Version Id */
            product_version_id: number;
            /** Ots Component Id */
            ots_component_id: number;
            /** Created By */
            created_by: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Ots Name */
            ots_name: string;
            /** Ots Version */
            ots_version: string;
            /** Official Website */
            official_website: string;
            /** Is Eol */
            is_eol: boolean;
        };
        /** ProductPageResponse */
        ProductPageResponse: {
            /** Items */
            items: components["schemas"]["ProductResponse"][];
            /** Total */
            total: number;
            /** Page */
            page: number;
            /** Page Size */
            page_size: number;
        };
        /** ProductResponse */
        ProductResponse: {
            /** Id */
            id: number;
            /** Product Code */
            product_code: string;
            /** Product Name */
            product_name: string;
            /** Description */
            description: string | null;
            /**
             * Status
             * @enum {string}
             */
            status: "active" | "disabled";
            /** Row Version */
            row_version: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** ProductUpdateRequest */
        ProductUpdateRequest: {
            /** Product Code */
            product_code: string;
            /** Product Name */
            product_name: string;
            /** Description */
            description?: string | null;
            /** Row Version */
            row_version: number;
        };
        /** ProductVersionResponse */
        ProductVersionResponse: {
            /** Id */
            id: number;
            /** Product Id */
            product_id: number;
            /** Version No */
            version_no: string;
            /** Description */
            description: string | null;
            /**
             * Primary Cvss Version
             * @constant
             */
            primary_cvss_version: "3.1";
            /** Owner Id */
            owner_id: number;
            /** Reviewer Id */
            reviewer_id: number;
            /**
             * Status
             * @enum {string}
             */
            status: "active" | "disabled";
            /** Row Version */
            row_version: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** PublicUserResponse */
        PublicUserResponse: {
            /** Id */
            id: number;
            /** Login Name */
            login_name: string;
            /** Display Name */
            display_name: string;
            /** Roles */
            roles: string[];
        };
        /** ScopeGrantRequest */
        ScopeGrantRequest: {
            /**
             * Scope Type
             * @enum {string}
             */
            scope_type: "product" | "version";
            /** Product Id */
            product_id: number;
            /** Product Version Id */
            product_version_id?: number | null;
        };
        /** ScopeResponse */
        ScopeResponse: {
            /** Id */
            id: number;
            /** User Id */
            user_id: number;
            /**
             * Scope Type
             * @enum {string}
             */
            scope_type: "product" | "version";
            /** Product Id */
            product_id: number;
            /** Product Version Id */
            product_version_id: number | null;
            /** Scope Key */
            scope_key: string;
            /** Created By */
            created_by: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Is Effective */
            is_effective: boolean;
        };
        /** ScopeSummaryResponse */
        ScopeSummaryResponse: {
            /** Is Global */
            is_global: boolean;
            /** Scopes */
            scopes: components["schemas"]["ScopeResponse"][];
            /** Effective Product Ids */
            effective_product_ids: number[];
            /** Effective Version Ids */
            effective_version_ids: number[];
        };
        /** TaskGenerationResponse */
        TaskGenerationResponse: {
            /** Schema Version */
            schema_version: string;
            /** Status */
            status: string;
            /** Task Inserted Count */
            task_inserted_count: number;
            /** Task Reassess Count */
            task_reassess_count: number;
            /** Task Updated Count */
            task_updated_count: number;
            /** Task Unchanged Count */
            task_unchanged_count: number;
            /** Task Skipped Count */
            task_skipped_count: number;
            /** Task Failed Count */
            task_failed_count: number;
            /** Skip Reason Counts */
            skip_reason_counts: {
                [key: string]: number;
            };
            /** Task Samples */
            task_samples: components["schemas"]["TaskSampleResponse"][];
            /** Truncated Task Count */
            truncated_task_count: number;
            /** Error Code */
            error_code: string | null;
        };
        /** TaskSampleResponse */
        TaskSampleResponse: {
            /** Vulnerability Id */
            vulnerability_id: number;
            /** Cve Id */
            cve_id: string;
            /** Product Id */
            product_id: number | null;
            /** Product Name */
            product_name: string | null;
            /** Product Version Id */
            product_version_id: number | null;
            /** Version No */
            version_no: string | null;
            /** Product Ots Id */
            product_ots_id: number | null;
            /** Owner Id */
            owner_id: number | null;
            /** Action */
            action: string;
            /** Reason */
            reason: string | null;
        };
        /** UserCreateRequest */
        UserCreateRequest: {
            /** Login Name */
            login_name: string;
            /** Display Name */
            display_name: string;
            /** Password */
            password: string;
            /** Roles */
            roles: ("admin" | "product_owner" | "reviewer")[];
        };
        /** UserDisableRequest */
        UserDisableRequest: {
            /** Row Version */
            row_version: number;
        };
        /** UserPageResponse */
        UserPageResponse: {
            /** Items */
            items: components["schemas"]["UserResponse"][];
            /** Total */
            total: number;
            /** Page */
            page: number;
            /** Page Size */
            page_size: number;
        };
        /** UserResponse */
        UserResponse: {
            /** Id */
            id: number;
            /** Login Name */
            login_name: string;
            /** Display Name */
            display_name: string;
            /** Roles */
            roles: ("admin" | "product_owner" | "reviewer")[];
            /**
             * Status
             * @enum {string}
             */
            status: "active" | "disabled";
            /** Last Login At */
            last_login_at: string | null;
            /** Row Version */
            row_version: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** UserUpdateRequest */
        UserUpdateRequest: {
            /** Display Name */
            display_name: string;
            /** Roles */
            roles: ("admin" | "product_owner" | "reviewer")[];
            /** Row Version */
            row_version: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** VersionCreateRequest */
        VersionCreateRequest: {
            /** Version No */
            version_no: string;
            /** Description */
            description?: string | null;
            /** Owner Id */
            owner_id: number;
            /** Reviewer Id */
            reviewer_id: number;
        };
        /** VersionUpdateRequest */
        VersionUpdateRequest: {
            /** Version No */
            version_no: string;
            /** Description */
            description?: string | null;
            /** Owner Id */
            owner_id: number;
            /** Reviewer Id */
            reviewer_id: number;
            /** Row Version */
            row_version: number;
        };
        /** VulnerabilityCandidateResponse */
        VulnerabilityCandidateResponse: {
            /** Vulnerability Id */
            vulnerability_id: number;
            /** Cve Id */
            cve_id: string;
            /** Ots Component Id */
            ots_component_id: number;
            /** Ots Name */
            ots_name: string;
            /** Ots Version */
            ots_version: string;
            /** Match Method */
            match_method: string;
            /** Match Basis */
            match_basis: string;
            /** Match Confidence */
            match_confidence: number | null;
            /** Match Evidence */
            match_evidence: {
                [key: string]: unknown;
            };
            /** First Seen Batch Id */
            first_seen_batch_id: number;
            /** First Seen Batch No */
            first_seen_batch_no: string;
            /** Last Seen Batch Id */
            last_seen_batch_id: number;
            /** Last Seen Batch No */
            last_seen_batch_no: string;
            /** Based On Source Modified At */
            based_on_source_modified_at: string | null;
        };
        /** VulnerabilityDetailResponse */
        VulnerabilityDetailResponse: {
            /** Id */
            id: number;
            /** Cve Id */
            cve_id: string;
            source: components["schemas"]["VulnerabilitySourceResponse"];
            cvss31: components["schemas"]["Cvss31Response"] | null;
            /** Cwes */
            cwes: unknown[];
            /** Affected Ranges */
            affected_ranges: unknown[];
            /** References */
            references: unknown[];
            kev: components["schemas"]["KevResponse"];
            /** Ai Analysis Suggestion */
            ai_analysis_suggestion: string | null;
            /** Candidates */
            candidates: components["schemas"]["VulnerabilityCandidateResponse"][];
            /** Candidate Disclaimer */
            candidate_disclaimer: string;
        };
        /** VulnerabilityListItemResponse */
        VulnerabilityListItemResponse: {
            /** Id */
            id: number;
            /** Cve Id */
            cve_id: string;
            /** Source Status */
            source_status: string;
            /** Description */
            description: string | null;
            /** Published At */
            published_at: string | null;
            /** Source Modified At */
            source_modified_at: string | null;
            /** Cvss31 Score */
            cvss31_score: number | null;
            /** Cvss31 Severity */
            cvss31_severity: string | null;
            /** Is Kev */
            is_kev: boolean;
            /** Visible Candidate Count */
            visible_candidate_count: number;
            /** Visible Task Count */
            visible_task_count: number;
        };
        /** VulnerabilityMatchDetailResponse */
        VulnerabilityMatchDetailResponse: {
            /** Vulnerability Id */
            vulnerability_id: number;
            /** Cve Id */
            cve_id: string;
            /** Candidates */
            candidates: components["schemas"]["CandidateDetailResponse"][];
            /** Unmatched Reason */
            unmatched_reason: string | null;
            /** Candidate Disclaimer */
            candidate_disclaimer: string;
        };
        /** VulnerabilityPageResponse */
        VulnerabilityPageResponse: {
            /** Items */
            items: components["schemas"]["VulnerabilityListItemResponse"][];
            /** Total */
            total: number;
            /** Page */
            page: number;
            /** Page Size */
            page_size: number;
        };
        /** VulnerabilitySourceResponse */
        VulnerabilitySourceResponse: {
            /** Identifier */
            identifier: string;
            /** Status */
            status: string;
            /** Description */
            description: string | null;
            /** Published At */
            published_at: string | null;
            /** Modified At */
            modified_at: string | null;
            /** Import Batch Id */
            import_batch_id: number;
            /** Import Batch No */
            import_batch_no: string;
        };
        /** WorkbenchSummaryResponse */
        WorkbenchSummaryResponse: {
            /** Pending Count */
            pending_count: number;
            /** Returned Count */
            returned_count: number;
            /** Reassess Count */
            reassess_count: number;
            /** Submitted Count */
            submitted_count: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    root__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    health_api_v1_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    login_api_v1_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublicUserResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    current_user_api_v1_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublicUserResponse"];
                };
            };
        };
    };
    logout_api_v1_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    list_users_api_v1_users_get: {
        parameters: {
            query?: {
                query?: string | null;
                status?: ("active" | "disabled") | null;
                role?: ("admin" | "product_owner" | "reviewer") | null;
                page?: number;
                page_size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserPageResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_user_api_v1_users_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_user_api_v1_users__user_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_user_api_v1_users__user_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserUpdateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reset_password_api_v1_users__user_id__reset_password_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PasswordResetRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    disable_user_api_v1_users__user_id__disable_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserDisableRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_products_api_v1_products_get: {
        parameters: {
            query?: {
                query?: string | null;
                status?: ("active" | "disabled") | null;
                page?: number;
                page_size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductPageResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_product_api_v1_products_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProductCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_product_api_v1_products__product_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                product_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_product_api_v1_products__product_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                product_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProductUpdateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    disable_product_api_v1_products__product_id__disable_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                product_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DisableRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_versions_api_v1_products__product_id__versions_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                product_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductVersionResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_version_api_v1_products__product_id__versions_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                product_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VersionCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductVersionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_version_api_v1_products__product_id__versions__version_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                product_id: number;
                version_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductVersionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_version_api_v1_products__product_id__versions__version_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                product_id: number;
                version_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VersionUpdateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductVersionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    disable_version_api_v1_products__product_id__versions__version_id__disable_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                product_id: number;
                version_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DisableRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductVersionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_ots_api_v1_ots_components_get: {
        parameters: {
            query?: {
                query?: string | null;
                is_eol?: boolean | null;
                page?: number;
                page_size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OtsPageResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_ots_api_v1_ots_components_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OtsCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OtsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_ots_api_v1_ots_components__ots_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ots_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OtsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_ots_api_v1_ots_components__ots_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ots_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OtsUpdateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OtsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    associated_versions_api_v1_ots_components__ots_id__product_versions_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ots_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OtsProductVersionResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_product_ots_api_v1_product_versions__version_id__ots_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                version_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductOtsResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_product_ots_api_v1_product_versions__version_id__ots_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                version_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProductOtsCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductOtsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    remove_product_ots_api_v1_product_versions__version_id__ots__relation_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                version_id: number;
                relation_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    product_ots_template_api_v1_product_ots_template_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    export_product_ots_api_v1_product_versions__version_id__ots_export_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                version_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    import_product_ots_api_v1_product_versions__version_id__ots_import_post: {
        parameters: {
            query?: never;
            header?: {
                "X-File-Name"?: string;
            };
            path: {
                version_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "text/csv": string;
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CsvImportResultResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_user_scopes_api_v1_users__user_id__scopes_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScopeSummaryResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    grant_user_scope_api_v1_users__user_id__scopes_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ScopeGrantRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScopeResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    revoke_user_scope_api_v1_users__user_id__scopes__scope_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: number;
                scope_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    current_scope_summary_api_v1_scopes_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScopeSummaryResponse"];
                };
            };
        };
    };
    preview_collector_scope_api_v1_collector_scope_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CollectorScopePreviewResponse"];
                };
            };
        };
    };
    export_collector_scope_api_v1_collector_scope_export_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 规范采集范围 CSV */
            200: {
                headers: {
                    "Content-Disposition"?: string;
                    "X-Scope-Export-ID"?: string;
                    "X-Content-SHA256"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "text/csv": string;
                };
            };
        };
    };
    validate_import_package_api_v1_import_packages_validate_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_validate_import_package_api_v1_import_packages_validate_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImportPackageResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    confirm_import_package_api_v1_import_packages__batch_id__confirm_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                batch_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImportPackageResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_import_package_api_v1_import_packages__batch_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                batch_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImportPackageResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    download_import_package_errors_api_v1_import_packages__batch_id__errors_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                batch_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 数据包校验错误清单 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/csv": string;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    preview_api_v1_import_packages__batch_id__ots_match_preview_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                batch_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MatchSummaryResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    execute_api_v1_import_packages__batch_id__ots_matches_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                batch_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MatchSummaryResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    result_api_v1_import_packages__batch_id__ots_match_result_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                batch_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MatchSummaryResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    detail_api_v1_vulnerabilities__vulnerability_id__ots_matches_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                vulnerability_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VulnerabilityMatchDetailResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    workbench_summary_api_v1_workbench_summary_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkbenchSummaryResponse"];
                };
            };
        };
    };
    import_summary_api_v1_workbench_import_summary_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImportSummaryResponse"];
                };
            };
        };
    };
    assessment_tasks_api_v1_assessments_tasks_get: {
        parameters: {
            query: {
                queue: "pending" | "returned" | "reassess" | "submitted";
                page?: number;
                page_size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AssessmentTaskPageResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    vulnerabilities_api_v1_vulnerabilities_get: {
        parameters: {
            query?: {
                cve?: string | null;
                ots_id?: number | null;
                product_id?: number | null;
                severity?: ("NONE" | "LOW" | "MEDIUM" | "HIGH" | "CRITICAL") | null;
                is_kev?: boolean | null;
                assessment_status?: ("pending" | "submitted" | "returned" | "completed" | "reassess") | null;
                published_from?: string | null;
                published_to?: string | null;
                modified_from?: string | null;
                modified_to?: string | null;
                page?: number;
                page_size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VulnerabilityPageResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    vulnerability_detail_api_v1_vulnerabilities__vulnerability_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                vulnerability_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VulnerabilityDetailResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
