CREATE TABLE import_batch (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    batch_no VARCHAR(100) NOT NULL,
    format_version VARCHAR(32) NOT NULL,
    package_file_name VARCHAR(255) NOT NULL,
    package_sha256 CHAR(64) NOT NULL,
    archive_path VARCHAR(1000) NULL,
    covered_from DATETIME(3) NULL,
    covered_to DATETIME(3) NULL,
    status VARCHAR(32) NOT NULL,
    result_json JSON NULL,
    error_json JSON NULL,
    scope_coverage_json JSON NULL,
    manifest_json JSON NULL,
    imported_by BIGINT UNSIGNED NOT NULL,
    started_at DATETIME(3) NULL,
    finished_at DATETIME(3) NULL,
    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
    CONSTRAINT pk_import_batch PRIMARY KEY (id),
    CONSTRAINT fk_import_batch_imported_by FOREIGN KEY (imported_by) REFERENCES app_user(id),
    CONSTRAINT ck_import_batch_status CHECK (status IN ('uploaded', 'validated', 'importing', 'succeeded', 'failed')),
    CONSTRAINT uk_import_batch_no UNIQUE (batch_no),
    CONSTRAINT uk_import_package_sha UNIQUE (package_sha256),
    INDEX idx_import_status_time (status, created_at),
    INDEX idx_import_covered_to (covered_to)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
