CREATE TABLE product_assessment (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    product_ots_id BIGINT UNSIGNED NOT NULL,
    vulnerability_id BIGINT UNSIGNED NOT NULL,
    revision_no INT UNSIGNED NOT NULL,
    parent_revision_id BIGINT UNSIGNED NULL,
    is_current TINYINT(1) NOT NULL,
    status VARCHAR(32) NOT NULL,
    owner_id BIGINT UNSIGNED NOT NULL,
    analysis_summary TEXT NULL,
    trigger_conditions TEXT NULL,
    affected_functions TEXT NULL,
    applicability VARCHAR(32) NOT NULL,
    applicability_basis TEXT NULL,
    product_impact TEXT NULL,
    existing_controls TEXT NULL,
    treatment VARCHAR(32) NULL,
    treatment_detail TEXT NULL,
    evidence_text TEXT NULL,
    cvss_version VARCHAR(8) NULL,
    environmental_score DECIMAL(3,1) NULL,
    environmental_vector VARCHAR(1000) NULL,
    cvss_metrics_json JSON NULL,
    calculator_version VARCHAR(64) NULL,
    based_on_source_modified_at DATETIME(3) NOT NULL,
    submitted_by BIGINT UNSIGNED NULL,
    submitted_at DATETIME(3) NULL,
    review_decision VARCHAR(16) NULL,
    review_comment TEXT NULL,
    reviewer_id BIGINT UNSIGNED NULL,
    reviewed_at DATETIME(3) NULL,
    reassess_reason VARCHAR(500) NULL,
    row_version INT UNSIGNED NOT NULL,
    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
    CONSTRAINT pk_product_assessment PRIMARY KEY (id),
    CONSTRAINT fk_assessment_product_ots FOREIGN KEY (product_ots_id) REFERENCES product_ots(id) ON UPDATE RESTRICT ON DELETE RESTRICT,
    CONSTRAINT fk_assessment_vulnerability FOREIGN KEY (vulnerability_id) REFERENCES vulnerability(id) ON UPDATE RESTRICT ON DELETE RESTRICT,
    CONSTRAINT fk_assessment_parent FOREIGN KEY (parent_revision_id) REFERENCES product_assessment(id) ON UPDATE RESTRICT ON DELETE RESTRICT,
    CONSTRAINT fk_assessment_owner FOREIGN KEY (owner_id) REFERENCES app_user(id) ON UPDATE RESTRICT ON DELETE RESTRICT,
    CONSTRAINT fk_assessment_submitter FOREIGN KEY (submitted_by) REFERENCES app_user(id) ON UPDATE RESTRICT ON DELETE RESTRICT,
    CONSTRAINT fk_assessment_reviewer FOREIGN KEY (reviewer_id) REFERENCES app_user(id) ON UPDATE RESTRICT ON DELETE RESTRICT,
    CONSTRAINT uk_assessment_revision UNIQUE (product_ots_id, vulnerability_id, revision_no),
    CONSTRAINT ck_assessment_current CHECK (is_current IN (0, 1)),
    CONSTRAINT ck_assessment_status CHECK (status IN ('pending', 'submitted', 'returned', 'completed', 'reassess')),
    CONSTRAINT ck_assessment_applicability CHECK (applicability IN ('affected', 'not_affected', 'partly_affected', 'pending')),
    CONSTRAINT ck_assessment_cvss_version CHECK (cvss_version IS NULL OR cvss_version IN ('3.1', '4.0')),
    CONSTRAINT ck_assessment_review_decision CHECK (review_decision IS NULL OR review_decision IN ('approved', 'returned')),
    INDEX idx_assessment_current_owner (is_current, owner_id, status, updated_at),
    INDEX idx_assessment_current_review (is_current, status, updated_at),
    INDEX idx_assessment_cross_product (vulnerability_id, is_current, status, product_ots_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
