<template>
  <main class="ots-page">
    <header><div><p>MASTER DATA / OTS</p><h1>OTS 主数据</h1><span>名称与版本共同标识共享组件；实际使用范围由产品版本关联决定。</span></div><button class="primary" data-action="create-ots" @click="openCreate">新建 OTS</button></header>
    <form class="filters" @submit.prevent="load(1)"><input v-model="filters.query" aria-label="检索 OTS" placeholder="名称或版本"><select v-model="filters.eol" aria-label="EOL 状态"><option value="">全部 EOL 状态</option><option value="false">未 EOL</option><option value="true">已 EOL</option></select><button>查询</button></form>
    <p v-if="loading">正在读取 OTS 目录…</p><p v-else-if="loadError" role="alert">OTS 目录暂时不可用，请稍后重试</p><p v-else-if="page.items.length===0">暂无 OTS 主数据</p>
    <section v-else class="workspace"><table><thead><tr><th>OTS</th><th>OTS 版本</th><th>官方网站</th><th>EOL</th><th>操作</th></tr></thead><tbody><tr v-for="item in page.items" :key="item.id"><td><strong>{{ item.ots_name }}</strong></td><td>{{ item.ots_version }}</td><td><a :href="item.official_website" target="_blank" rel="noreferrer">{{ item.official_website }}</a></td><td><span class="status" :class="{eol:item.is_eol}">{{ item.is_eol?'已 EOL':'未 EOL' }}</span></td><td class="actions"><button :aria-label="`编辑${item.ots_name}`" @click="openEdit(item)">编辑</button><button :aria-label="`查看${item.ots_name}关联产品`" @click="showRelations(item)">关联产品</button></td></tr></tbody></table><footer v-if="page.total>page.page_size"><button :disabled="page.page===1" @click="load(page.page-1)">上一页</button><span>第 {{ page.page }} 页</span><button :disabled="page.page*page.page_size>=page.total" @click="load(page.page+1)">下一页</button></footer></section>
    <div v-if="editor.open" class="modal" @click.self="editor.open=false"><section class="dialog" role="dialog" aria-modal="true"><h2>{{ editor.mode==='create'?'新建 OTS':'编辑 OTS' }}</h2><form data-form="ots-editor" @submit.prevent="save"><label>OTS 名称<input v-model.trim="editor.name" name="ots_name" required maxlength="200"></label><label>OTS 版本<input v-model.trim="editor.version" name="ots_version" required maxlength="200"></label><label>官方网站<input v-model.trim="editor.website" name="official_website" type="url" required maxlength="1000"></label><label class="check"><input v-model="editor.isEol" name="is_eol" type="checkbox">已进入 EOL</label><p class="shared-note">编辑会影响所有关联产品版本。平台不提供 OTS 停用或删除。</p><p v-if="editor.error" role="alert">{{ editor.error }}</p><div v-if="editor.conflict" data-state="conflict"><strong>数据已被其他管理员更新</strong><p>已读取最新版本，但保留了尚未保存的输入。确认后可再次提交。</p></div><div class="dialog-actions"><button type="button" @click="editor.open=false">取消</button><button class="primary" type="submit">保存</button></div></form></section></div>
    <div v-if="relations.open" class="modal" @click.self="relations.open=false"><section class="dialog wide" role="dialog" aria-modal="true" aria-label="关联产品版本"><h2>{{ relations.item?.ots_name }} · 关联产品版本</h2><p v-if="relations.loading">正在读取关联…</p><p v-else-if="relations.items.length===0">尚未被产品版本使用</p><table v-else><thead><tr><th>产品</th><th>版本</th><th>状态</th></tr></thead><tbody><tr v-for="item in relations.items" :key="item.product_ots_id"><td>{{ item.product_name }}<small>{{ item.product_code }}</small></td><td>{{ item.version_no }}</td><td>{{ item.status==='active'?'启用':'已停用' }}</td></tr></tbody></table><button @click="relations.open=false">关闭</button></section></div>
  </main>
</template>

<script setup lang="ts">
import { onMounted, reactive, ref } from 'vue'
import { createOts, getOts, listOts, listOtsProductVersions, OtsApiError, updateOts, type Ots, type OtsPage, type OtsProductVersion } from '../api/ots'
const filters=reactive({query:'',eol:''});const page=reactive<OtsPage>({items:[],total:0,page:1,page_size:20});const loading=ref(true);const loadError=ref(false)
const editor=reactive({open:false,mode:'create' as'create'|'edit',id:0,name:'',version:'',website:'',isEol:false,rowVersion:1,error:'',conflict:false})
const relations=reactive({open:false,item:null as Ots|null,items:[] as OtsProductVersion[],loading:false})
onMounted(()=>load(1))
async function load(nextPage:number){loading.value=true;loadError.value=false;try{Object.assign(page,await listOts({query:filters.query,isEol:filters.eol===''?undefined:filters.eol==='true',page:nextPage,pageSize:page.page_size}))}catch{loadError.value=true}finally{loading.value=false}}
function openCreate(){Object.assign(editor,{open:true,mode:'create',id:0,name:'',version:'',website:'',isEol:false,rowVersion:1,error:'',conflict:false})}
function openEdit(item:Ots){Object.assign(editor,{open:true,mode:'edit',id:item.id,name:item.ots_name,version:item.ots_version,website:item.official_website,isEol:item.is_eol,rowVersion:item.row_version,error:'',conflict:false})}
async function save(){editor.error='';editor.conflict=false;const body={ots_name:editor.name,ots_version:editor.version,official_website:editor.website,is_eol:editor.isEol};try{if(editor.mode==='create')await createOts(body);else await updateOts(editor.id,{...body,row_version:editor.rowVersion});editor.open=false;await load(page.page)}catch(e){if(e instanceof OtsApiError&&e.code==='OTS_VERSION_CONFLICT'&&editor.mode==='edit'){editor.conflict=true;const latest=await getOts(editor.id).catch(()=>null);if(latest)editor.rowVersion=latest.row_version}else if(e instanceof OtsApiError&&e.code==='OTS_COMPONENT_CONFLICT')editor.error='同名同版本 OTS 已存在';else editor.error='保存失败，请检查输入后重试'}}
async function showRelations(item:Ots){relations.open=true;relations.item=item;relations.loading=true;try{relations.items=await listOtsProductVersions(item.id)}catch{relations.items=[]}finally{relations.loading=false}}
</script>

<style scoped>
.ots-page{max-width:1280px;margin:auto;padding:48px 32px}.ots-page>header{display:flex;justify-content:space-between;align-items:end}.ots-page header p{color:var(--brand-red);font-weight:900;letter-spacing:.16em}.ots-page header span{color:var(--text-muted)}h1{font-size:52px;margin:8px 0;color:var(--ink)}button,input,select{font:inherit;min-height:42px;padding:8px 12px;border:1px solid var(--line-strong);background:#fff}.primary{background:var(--brand-red);color:#fff}.filters{display:flex;gap:12px;margin:28px 0}.filters input{min-width:300px}.workspace,.dialog{padding:24px;background:#fff;border:1px solid var(--line-strong);box-shadow:var(--shadow-card)}table{width:100%;border-collapse:collapse}th,td{padding:14px;border-bottom:1px solid var(--line);text-align:left}small{display:block;color:var(--text-muted)}a{color:var(--brand-red-deep);word-break:break-all}.actions,.dialog-actions{display:flex;gap:8px}.status{font-weight:700}.status.eol{color:var(--brand-red)}.workspace footer{display:flex;justify-content:center;gap:16px;padding-top:18px}.modal{position:fixed;inset:0;z-index:50;display:grid;place-items:center;background:#0008}.dialog{width:min(560px,calc(100% - 32px));max-height:90vh;overflow:auto}.dialog.wide{width:min(820px,calc(100% - 32px))}.dialog form,.dialog label{display:grid;gap:8px}.dialog form{gap:14px}.dialog label.check{display:flex;align-items:center}.shared-note{padding:12px;background:var(--paper-warm);color:var(--text-muted);border-left:3px solid var(--brand-red)}[data-state=conflict]{padding:12px;border-left:4px solid var(--brand-red);background:#fff1f2}@media(max-width:700px){.ots-page>header,.filters{align-items:stretch;flex-direction:column}.ots-page{padding:24px 14px}.actions{flex-wrap:wrap}}
</style>
