<template>
  <main class="products-page">
    <header><div><p>MASTER DATA / PRODUCTS</p><h1>产品管理</h1></div><button class="primary" data-action="create-product" @click="openProductCreate">新建产品</button></header>
    <form class="filters" @submit.prevent="loadProducts(1)"><input v-model="filters.query" aria-label="检索产品" placeholder="产品编号或名称"><select v-model="filters.status" aria-label="产品状态"><option value="">全部状态</option><option value="active">启用</option><option value="disabled">已停用</option></select><button>查询</button></form>
    <p v-if="loading">正在读取产品目录…</p><p v-else-if="loadError" role="alert">产品目录暂时不可用，请稍后重试</p><p v-else-if="page.items.length===0">暂无产品</p>
    <section v-else class="workspace"><table><thead><tr><th>产品</th><th>状态</th><th>操作</th></tr></thead><tbody><tr v-for="product in page.items" :key="product.id"><td><strong>{{ product.product_name }}</strong><small>{{ product.product_code }} · v{{ product.row_version }}</small></td><td>{{ statusName(product.status) }}</td><td class="actions"><button :aria-label="`编辑${product.product_name}`" @click="openProductEdit(product)">编辑</button><button :aria-label="`维护${product.product_name}版本`" @click="openVersions(product)">版本维护</button><button v-if="product.status==='active'" :aria-label="`停用${product.product_name}`" @click="disableCurrentProduct(product)">停用</button></td></tr></tbody></table><footer v-if="page.total>page.page_size"><button :disabled="page.page===1" @click="loadProducts(page.page-1)">上一页</button><span>第 {{ page.page }} 页</span><button :disabled="page.page*page.page_size>=page.total" @click="loadProducts(page.page+1)">下一页</button></footer></section>

    <div v-if="productEditor.open" class="modal" @click.self="productEditor.open=false"><section class="dialog" role="dialog" aria-modal="true"><h2>{{ productEditor.mode==='create' ? `产品建档 · 第 ${productEditor.step} 步` : '编辑产品' }}</h2><form data-form="product-editor" @submit.prevent="saveProduct"><template v-if="productEditor.mode==='edit'||productEditor.step===1"><label>产品编号<input v-model.trim="productEditor.code" name="product_code" required></label><label>产品名称<input v-model.trim="productEditor.name" name="product_name" required></label><label>说明<textarea v-model="productEditor.description" /></label></template><VersionFields v-else v-model:version-no="productEditor.versionNo" v-model:owner-id="productEditor.ownerId" v-model:reviewer-id="productEditor.reviewerId" :owners="owners" :reviewers="reviewers" /><p v-if="productEditor.error" role="alert">{{ productEditor.error }}</p><div v-if="productEditor.conflict" data-state="conflict"><strong>数据已被其他管理员更新</strong><p>已读取最新版本，但保留了尚未保存的输入。确认后可再次提交。</p></div><button type="button" @click="productEditor.open=false">取消</button><button class="primary" type="submit">{{ productEditor.mode==='create'&&productEditor.step===1 ? '下一步' : '保存' }}</button></form></section></div>

    <div v-if="versionDialog.open" class="modal" @click.self="closeVersions"><section class="dialog wide" role="dialog" aria-modal="true" aria-label="版本维护"><header><h2>版本维护 · {{ versionDialog.product?.product_name }}</h2><button class="primary" data-action="create-version" @click="openVersionCreate">新建版本</button></header><p v-if="versionDialog.items.length===0">暂无产品版本</p><table v-else><thead><tr><th>版本号</th><th>负责人</th><th>审核人</th><th>状态</th><th>操作</th></tr></thead><tbody><tr v-for="item in versionDialog.items" :key="item.id"><td>{{ item.version_no }}</td><td>{{ userName(owners,item.owner_id) }}</td><td>{{ userName(reviewers,item.reviewer_id) }}</td><td>{{ statusName(item.status) }}</td><td class="actions"><button :aria-label="`编辑版本${item.version_no}`" @click="openVersionEdit(item)">编辑</button><button v-if="item.status==='active'" :aria-label="`停用版本${item.version_no}`" @click="disableCurrentVersion(item)">停用</button></td></tr></tbody></table><button @click="closeVersions">关闭</button></section></div>

    <div v-if="versionEditor.open" class="modal top"><section class="dialog" role="dialog" aria-modal="true"><h2>{{ versionEditor.mode==='create'?'新建版本':'编辑版本' }}</h2><form data-form="version-editor" @submit.prevent="saveVersion"><VersionFields v-model:version-no="versionEditor.versionNo" v-model:owner-id="versionEditor.ownerId" v-model:reviewer-id="versionEditor.reviewerId" :owners="owners" :reviewers="reviewers" /><label>说明<textarea v-model="versionEditor.description" /></label><p v-if="versionEditor.error" role="alert">{{ versionEditor.error }}</p><div v-if="versionEditor.conflict" data-state="conflict"><strong>数据已被其他管理员更新</strong><p>已读取最新版本，但保留了尚未保存的输入。确认后可再次提交。</p></div><button type="button" @click="versionEditor.open=false">取消</button><button class="primary" type="submit">保存版本</button></form></section></div>
  </main>
</template>

<script setup lang="ts">
import { defineComponent, h, onMounted, reactive, ref } from 'vue'
import { createProduct,createVersion,disableProduct,disableVersion,getProduct,getVersion,listProducts,listVersions,ProductApiError,updateProduct,updateVersion,type Product,type ProductPage,type ProductVersion } from '../api/products'
import { listUsers,type ManagedUser } from '../api/users'
const VersionFields=defineComponent({props:{versionNo:{type:String,required:true},ownerId:{type:Number,required:true},reviewerId:{type:Number,required:true},owners:{type:Array as()=>ManagedUser[],required:true},reviewers:{type:Array as()=>ManagedUser[],required:true}},emits:['update:versionNo','update:ownerId','update:reviewerId'],setup(p,{emit}){const select=(name:string,value:number,users:ManagedUser[],event:'update:ownerId'|'update:reviewerId')=>h('select',{name,value,required:true,onChange:(e:Event)=>emit(event,Number((e.target as HTMLSelectElement).value))},[h('option',{value:0},'请选择'),...users.map(u=>h('option',{value:u.id},u.display_name))]);return()=>h('div',{class:'version-fields'},[h('label',['版本号',h('input',{name:'version_no',value:p.versionNo,required:true,onInput:(e:Event)=>emit('update:versionNo',(e.target as HTMLInputElement).value)})]),h('label',['负责人',select('owner_id',p.ownerId,p.owners,'update:ownerId')]),h('label',['审核人',select('reviewer_id',p.reviewerId,p.reviewers,'update:reviewerId')])])}})
const filters=reactive({query:'',status:''});const page=reactive<ProductPage>({items:[],total:0,page:1,page_size:20});const loading=ref(true);const loadError=ref(false);const owners=ref<ManagedUser[]>([]);const reviewers=ref<ManagedUser[]>([])
const productEditor=reactive({open:false,mode:'create' as'create'|'edit',step:1,id:0,code:'',name:'',description:'',rowVersion:1,versionNo:'',ownerId:0,reviewerId:0,error:'',conflict:false})
const versionDialog=reactive({open:false,product:null as Product|null,items:[] as ProductVersion[]});const versionEditor=reactive({open:false,mode:'create' as'create'|'edit',id:0,versionNo:'',description:'',ownerId:0,reviewerId:0,rowVersion:1,error:'',conflict:false})
onMounted(()=>Promise.all([loadProducts(1),loadPeople()]))
async function loadProducts(n:number){loading.value=true;loadError.value=false;try{Object.assign(page,await listProducts({query:filters.query,status:filters.status,page:n,pageSize:page.page_size}))}catch{loadError.value=true}finally{loading.value=false}}
async function loadPeople(){try{const[o,r]=await Promise.all([listUsers({status:'active',role:'product_owner'}),listUsers({status:'active',role:'reviewer'})]);owners.value=o.items;reviewers.value=r.items}catch{owners.value=[];reviewers.value=[]}}
function openProductCreate(){Object.assign(productEditor,{open:true,mode:'create',step:1,id:0,code:'',name:'',description:'',rowVersion:1,versionNo:'',ownerId:0,reviewerId:0,error:'',conflict:false})}
function openProductEdit(p:Product){Object.assign(productEditor,{open:true,mode:'edit',step:1,id:p.id,code:p.product_code,name:p.product_name,description:p.description??'',rowVersion:p.row_version,error:'',conflict:false})}
async function saveProduct(){productEditor.error='';productEditor.conflict=false;try{if(productEditor.mode==='create'&&productEditor.step===1){const saved=await createProduct({product_code:productEditor.code,product_name:productEditor.name,description:productEditor.description||null});productEditor.id=saved.id;productEditor.step=2;return}if(productEditor.mode==='create'){validatePeople(productEditor.ownerId,productEditor.reviewerId);await createVersion(productEditor.id,{version_no:productEditor.versionNo,owner_id:productEditor.ownerId,reviewer_id:productEditor.reviewerId});productEditor.open=false}else{await updateProduct(productEditor.id,{product_code:productEditor.code,product_name:productEditor.name,description:productEditor.description||null,row_version:productEditor.rowVersion});productEditor.open=false}await loadProducts(page.page)}catch(e){if(e instanceof ProductApiError&&e.code==='PRODUCT_VERSION_CONFLICT'&&productEditor.mode==='edit'){productEditor.conflict=true;const latest=await getProduct(productEditor.id).catch(()=>null);if(latest)productEditor.rowVersion=latest.row_version}else productEditor.error=errorMessage(e)}}
async function openVersions(p:Product){versionDialog.product=p;versionDialog.items=await listVersions(p.id);versionDialog.open=true}function closeVersions(){versionDialog.open=false;versionEditor.open=false}
function openVersionCreate(){Object.assign(versionEditor,{open:true,mode:'create',id:0,versionNo:'',description:'',ownerId:0,reviewerId:0,rowVersion:1,error:'',conflict:false})}function openVersionEdit(v:ProductVersion){Object.assign(versionEditor,{open:true,mode:'edit',id:v.id,versionNo:v.version_no,description:v.description??'',ownerId:v.owner_id,reviewerId:v.reviewer_id,rowVersion:v.row_version,error:'',conflict:false})}
async function saveVersion(){if(!versionDialog.product)return;versionEditor.error='';versionEditor.conflict=false;try{validatePeople(versionEditor.ownerId,versionEditor.reviewerId);const body={version_no:versionEditor.versionNo,description:versionEditor.description||null,owner_id:versionEditor.ownerId,reviewer_id:versionEditor.reviewerId};if(versionEditor.mode==='create')await createVersion(versionDialog.product.id,body);else await updateVersion(versionDialog.product.id,versionEditor.id,{...body,row_version:versionEditor.rowVersion});versionEditor.open=false;await openVersions(versionDialog.product)}catch(e){if(e instanceof ProductApiError&&e.code==='PRODUCT_VERSION_CONFLICT'&&versionEditor.mode==='edit'){versionEditor.conflict=true;const latest=await getVersion(versionDialog.product.id,versionEditor.id).catch(()=>null);if(latest)versionEditor.rowVersion=latest.row_version}else versionEditor.error=errorMessage(e)}}
async function disableCurrentProduct(p:Product){if(!confirm(`停用 ${p.product_name}？历史记录将保留。`))return;await disableProduct(p.id,p.row_version);await loadProducts(page.page)}async function disableCurrentVersion(v:ProductVersion){if(!versionDialog.product||!confirm(`停用版本 ${v.version_no}？历史记录将保留。`))return;await disableVersion(versionDialog.product.id,v.id,v.row_version);await openVersions(versionDialog.product)}
function validatePeople(o:number,r:number){if(!owners.value.some(u=>u.id===o)||!reviewers.value.some(u=>u.id===r))throw new ProductApiError('PRODUCT_ASSIGNMENT_INVALID',422)}function errorMessage(e:unknown){if(e instanceof ProductApiError&&e.code==='PRODUCT_ASSIGNMENT_INVALID')return'负责人必须启用且具备产品负责人角色；审核人必须启用且具备审核人角色';if(e instanceof ProductApiError&&e.code==='PRODUCT_CODE_CONFLICT')return'产品编号已存在，请更换后重试';if(e instanceof ProductApiError&&e.code==='PRODUCT_VERSION_CONFLICT')return'同一产品下版本号已存在，或数据已被其他管理员更新';return'保存失败，请稍后重试'}function userName(users:ManagedUser[],id:number){return users.find(u=>u.id===id)?.display_name??`用户 #${id}`}function statusName(s:string){return s==='active'?'启用':'已停用'}
</script>

<style scoped>
.products-page{max-width:1280px;margin:auto;padding:48px 32px}.products-page>header,.dialog>header{display:flex;justify-content:space-between;align-items:end}.products-page header p{color:var(--brand-red);font-weight:900;letter-spacing:.16em}h1{font-size:52px;margin:8px 0;color:var(--ink)}button,input,select,textarea{font:inherit;min-height:42px;padding:8px 12px;border:1px solid var(--line-strong)}.primary{background:var(--brand-red);color:#fff}.filters{display:flex;gap:12px;margin:28px 0}.filters input{min-width:300px}.workspace,.dialog{padding:24px;background:#fff;border:1px solid var(--line-strong);box-shadow:var(--shadow-card)}table{width:100%;border-collapse:collapse}th,td{padding:14px;border-bottom:1px solid var(--line);text-align:left}small{display:block;color:var(--text-muted)}.actions{display:flex;gap:8px}.workspace footer{display:flex;justify-content:center;gap:16px;padding-top:18px}.modal{position:fixed;inset:0;z-index:50;display:grid;place-items:center;background:#0008}.modal.top{z-index:60}.dialog{width:min(560px,calc(100% - 32px));max-height:90vh;overflow:auto}.dialog.wide{width:min(980px,calc(100% - 32px))}.dialog form,.version-fields{display:grid;gap:14px}.dialog label{display:grid;gap:6px}.dialog [data-state=conflict]{padding:12px;border-left:4px solid var(--brand-red);background:#fff1f2}@media(max-width:700px){.products-page>header,.filters{align-items:stretch;flex-direction:column}.products-page{padding:24px 14px}.actions{flex-wrap:wrap}}
</style>
