<template>
  <main class="operations-page">
    <header><div><p>SYSTEM MANAGEMENT / OPERATIONS</p><h1>系统运行状态</h1><span>查看应用、数据库、磁盘、备份与导入的当前观测结果。</span></div><button data-action="refresh" :disabled="loading" @click="load">{{ loading?'刷新中…':'刷新状态' }}</button></header>
    <p v-if="error" class="notice error" role="alert">{{ error }}<span v-if="stale">上次数据已标记为陈旧，不代表当前正常。</span></p>
    <p v-if="loading && !operations" class="notice" aria-live="polite">正在探测运行状态…</p>
    <template v-if="operations">
      <section class="overview" :data-status="stale?'unknown':operations.overall_status"><small>OVERALL STATUS</small><strong>{{ stale?'状态陈旧':statusNames[operations.overall_status] }}</strong><span>观测时间 {{ formatTime(operations.observed_at) }}</span></section>
      <section class="grid" aria-label="运行状态分项"><article v-for="item in cards" :key="item.key" :data-status="stale?'unknown':item.value.status"><div><small>{{ item.kicker }}</small><span>{{ stale?'陈旧':statusNames[item.value.status] }}</span></div><h2>{{ item.label }}</h2><p>{{ item.value.summary }}</p><dl><template v-for="field in fields(item.value)" :key="field.label"><dt>{{ field.label }}</dt><dd>{{ field.value }}</dd></template></dl></article></section>
    </template>
  </main>
</template>

<script setup lang="ts">
import { computed, onMounted, ref } from 'vue'
import { AuditOperationsApiError, getSystemOperations, type OperationComponent, type SystemOperations } from '../api/auditOperations'
const operations=ref<SystemOperations|null>(null),loading=ref(true),error=ref(''),stale=ref(false)
const statusNames:Record<string,string>={ok:'正常',warning:'警告',error:'故障',unknown:'未知'}
const cards=computed(()=>operations.value?[{key:'application',kicker:'BUILD',label:'应用版本',value:operations.value.application},{key:'database',kicker:'MYSQL',label:'数据库',value:operations.value.database},{key:'disk',kicker:'STORAGE',label:'磁盘空间',value:operations.value.disk},{key:'backup',kicker:'BACKUP',label:'最近备份',value:operations.value.backup},{key:'latest_import',kicker:'IMPORT',label:'最近导入',value:operations.value.latest_import},{key:'latest_failure',kicker:'FAILURE',label:'最近失败',value:operations.value.latest_failure}]:[])
onMounted(load)
async function load():Promise<void>{loading.value=true;error.value='';try{operations.value=await getSystemOperations();stale.value=false}catch(cause){stale.value=operations.value!==null;error.value=cause instanceof AuditOperationsApiError&&cause.status===403?'无权访问系统运行信息。':'运行状态暂时不可用，请稍后重试。'}finally{loading.value=false}}
function formatTime(value:string|null|undefined):string{return value?new Date(value).toLocaleString('zh-CN'):'—'}
function bytes(value:number|null|undefined):string{if(value==null)return '—';const units=['B','KB','MB','GB','TB'];let size=value,index=0;while(size>=1024&&index<units.length-1){size/=1024;index++}return `${size.toFixed(index?1:0)} ${units[index]}`}
function fields(item:OperationComponent):Array<{label:string,value:string}>{const result=[] as Array<{label:string,value:string}>;if(item.version)result.push({label:'版本',value:item.version});if(item.commit)result.push({label:'构建标识',value:item.commit});if(item.latency_ms!=null)result.push({label:'探测耗时',value:`${item.latency_ms} ms`});if(item.free_bytes!=null)result.push({label:'剩余空间',value:`${bytes(item.free_bytes)} / ${bytes(item.total_bytes)}`});if(item.used_percent!=null)result.push({label:'使用率',value:`${item.used_percent}%`});if(item.batch_no)result.push({label:'批次',value:`${item.batch_no} · ${item.batch_status??''}`});if(item.file_name)result.push({label:'文件',value:item.file_name});if(item.size_bytes!=null)result.push({label:'大小',value:bytes(item.size_bytes)});if(item.finished_at)result.push({label:'完成时间',value:formatTime(item.finished_at)});if(item.error_code)result.push({label:'错误码',value:item.error_code});return result}
</script>

<style scoped>
.operations-page{max-width:1160px;margin:0 auto;padding:48px 32px}.operations-page header{display:flex;align-items:end;justify-content:space-between;gap:24px}.operations-page header p,.overview small,.grid small{color:var(--brand-red);font-size:10px;font-weight:900;letter-spacing:.16em}h1{margin:8px 0;color:var(--ink);font:750 58px/1 var(--font-display)}header span{color:var(--text-muted)}header button{min-height:42px;padding:0 18px;border:1px solid var(--brand-red);color:#fff;background:var(--brand-red);font-weight:800}.notice{margin-top:24px;padding:16px;border-left:4px solid var(--line-strong);background:#fff}.notice.error{border-color:var(--brand-red);color:var(--danger)}.notice span{display:block;margin-top:6px}.overview{display:grid;grid-template-columns:1fr auto;gap:6px;margin-top:30px;padding:24px;border-left:6px solid var(--line-strong);background:#202428;color:#fff}.overview strong{font-size:30px}.overview>span{grid-column:2;grid-row:1/3;align-self:center;color:rgba(255,255,255,.55)}[data-status=ok]{border-color:var(--success)}[data-status=warning],[data-status=unknown]{border-color:#c88208}[data-status=error]{border-color:var(--brand-red)}.grid{display:grid;grid-template-columns:repeat(3,1fr);gap:14px;margin-top:16px}.grid article{min-height:240px;padding:22px;border:1px solid var(--line-strong);border-top-width:5px;background:#fff}.grid article>div{display:flex;justify-content:space-between}.grid article>div span{font-size:11px;font-weight:900}.grid h2{margin:26px 0 8px;color:var(--ink)}.grid p{min-height:38px;color:var(--text-muted);font-size:12px}.grid dl{display:grid;grid-template-columns:75px 1fr;gap:7px;margin-top:20px;font-size:11px}.grid dt{color:var(--text-muted)}.grid dd{margin:0;word-break:break-word}@media(max-width:880px){.grid{grid-template-columns:1fr 1fr}}@media(max-width:620px){.operations-page{padding:28px 14px}.operations-page header{align-items:start;flex-direction:column}.grid{grid-template-columns:1fr}h1{font-size:42px}.overview{grid-template-columns:1fr}.overview>span{grid-column:1;grid-row:auto}}
</style>
